# Generated by Django 5.1.6 on 2025-02-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tutorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="static/tutorial"
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(max_length=250)),
                ("link", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("Lifestyle", "Lifestyle"),
                    ("Travel", "Travel"),
                    ("Food", "Food"),
                    ("Health", "Health"),
                    ("Technology", "Technology"),
                ],
                default="Lifestyle",
                max_length=20,
            ),
        ),
    ]
