# Generated by Django 5.1.6 on 2025-02-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_tutorial_post_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="posts/%Y/%m/%d/"),
        ),
    ]
